version: "3.9"
services:
  api:
    build: .
    ports:
      - "4000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development

    depends_on:
      - redis
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis

  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
